nfs_mount_enabled: true

webimage_extra_packages: [--no-install-recommends cron]

hooks:
  post-start:
#    - exec: sudo apt-get -qq update
#    - exec: sudo apt-get -qq install -y --no-install-recommends cron
#    - exec: sudo apt-get -qq autoremove -y && sudo apt-get -qq clean -y

    - exec: sudo cp /mnt/ddev_config/cron/typo3 /etc/cron.d/typo3
    - exec: sudo chmod 0600 /etc/cron.d/typo3
    - exec: sudo service cron start
