version: '3.6'

services:
  web:
    command:
      - /bin/bash
      - -c
      - ( while true; do sleep 60; /var/www/html/vendor/bin/typo3 scheduler:run; done )& /start.sh

# from Jonas Eberle on Slack
