APIVersion: v1.10.1
name: ddev-typo3
type: typo3
docroot: public
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: "Europe/Berlin"

hooks:
  post-start:
    - exec: sudo apt-get -y update
    - exec: sudo chmod 0600 /etc/cron.d/typo3
    - exec: sudo apt-get -y install --no-install-recommends cron
    - exec: sudo apt-get -y clean
    - exec: sudo service cron start
