version: '3.6'

services:
  web:
    environment:
      - PHP_IDE_CONFIG=serverName=${DDEV_SITENAME}.ddev.site
    volumes:
      # add php xdebug profile path
      - ./php-profiles/:/tmp/debug/:delegated
