version: '3.6'

services:
  mysql:
    hostname: ${DDEV_SITENAME}-mysql
    image: mysql:5.7
    container_name: ddev-${DDEV_SITENAME}-mysql
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ./data/mysql/:/var/lib/mysql:delegated
      - .:/mnt/ddev_config
    ports:
      - 127.0.0.1:$DDEV_HOST_DB_PORT:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: $DDEV_DBAIMAGE
    container_name: ddev-${DDEV_SITENAME}-phpmyadmin
    ports:
      - "80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=db
      - PMA_PASSWORD=db
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - TZ=Europe/Berlin
      # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.site:<port>
      - HTTP_EXPOSE=$DDEV_PHPMYADMIN_PORT:8036